spring:
  application:
    name: YarA
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    username: test
    password: 1234
    url: jdbc:postgresql://localhost:5432/testDB